package com.deskdb.core;

import com.deskdb.mapping.annotations.Id;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.Serializable;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for DeskDB object persistence functionality using ObjectStore.
 */
public class DeskDBObjectPersistenceTest {

    private DeskDB db;
    private Path dbPath;

    @BeforeEach
    public void setUp() throws Exception {
        dbPath = Files.createTempDirectory("test_db");
        Path dbFile = dbPath.resolve("test.deskdb");
        db = DeskDB.open(dbFile);
    }

    @AfterEach
    public void tearDown() throws Exception {
        if (db != null && !db.isClosed()) {
            try {
                db.close();
            } catch (Exception e) {
                // Ignore close errors
            }
        }
        if (dbPath != null && Files.exists(dbPath)) {
            // Clean up all files in directory
            Files.walk(dbPath)
                .sorted((a, b) -> b.compareTo(a))
                .forEach(path -> {
                    try {
                        Files.deleteIfExists(path);
                    } catch (Exception e) {
                        // Ignore delete errors
                    }
                });
        }
    }

    @Test
    public void testPersistAndFindObject() throws Exception {
        Person person = new Person();
        person.setName("John Doe");
        person.setAge(30);

        Object id = db.persist(person);
        assertNotNull(id);

        Person found = db.find(Person.class, id);
        assertNotNull(found);
        assertEquals("John Doe", found.getName());
        assertEquals(30, found.getAge());
        assertEquals(id, found.getId());
    }

    @Test
    public void testPersistMultipleObjects() throws Exception {
        Person person1 = new Person();
        person1.setName("Alice");
        person1.setAge(25);

        Person person2 = new Person();
        person2.setName("Bob");
        person2.setAge(35);

        db.persist(person1);
        db.persist(person2);

        List<Person> all = db.findAll(Person.class);
        assertEquals(2, all.size());
    }

    @Test
    public void testUpdateObject() throws Exception {
        Person person = new Person();
        person.setName("Original");
        person.setAge(20);

        db.persist(person);
        assertNotNull(person.getId());

        person.setName("Updated");
        person.setAge(30);
        db.update(person);

        Person found = db.find(Person.class, person.getId());
        assertNotNull(found);
        assertEquals("Updated", found.getName());
        assertEquals(30, found.getAge());
    }

    @Test
    public void testRemoveObject() throws Exception {
        Person person = new Person();
        person.setName("To Delete");
        person.setAge(40);

        db.persist(person);
        Object id = person.getId();

        boolean removed = db.remove(person);
        assertTrue(removed);

        Person found = db.find(Person.class, id);
        assertNull(found);
    }

    @Test
    public void testRemoveByClassAndId() throws Exception {
        Person person = new Person();
        person.setName("To Delete");
        person.setAge(40);

        db.persist(person);
        Object id = person.getId();

        boolean removed = db.remove(Person.class, id);
        assertTrue(removed);

        Person found = db.find(Person.class, id);
        assertNull(found);
    }

    @Test
    public void testFindNonExistentObject() throws Exception {
        Person found = db.find(Person.class, 999L);
        assertNull(found);
    }

    @Test
    public void testFindAllEmpty() throws Exception {
        List<Person> all = db.findAll(Person.class);
        assertTrue(all.isEmpty());
    }

    @Test
    public void testAutoGeneratedIdsAreUnique() throws Exception {
        Person person1 = new Person();
        person1.setName("Person 1");
        person1.setAge(20);

        Person person2 = new Person();
        person2.setName("Person 2");
        person2.setAge(30);

        db.persist(person1);
        db.persist(person2);

        assertNotEquals(person1.getId(), person2.getId());
    }

    // Test entity class
    public static class Person implements Serializable {
        @Id
        private Long id;
        private String name;
        private int age;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public int getAge() {
            return age;
        }

        public void setAge(int age) {
            this.age = age;
        }
    }
}
