package com.deskdb.jdbc;

import java.sql.*;
import java.util.Map;

/**
 * Implementación de Statement JDBC para DeskDB.
 */
public class DeskDBStatement implements Statement {

    private final DeskDBConnection connection;
    private boolean closed = false;
    private int maxRows = 0;
    private int fetchSize = 0;
    private ResultSet currentResultSet = null;
    private long updateCount = -1;

    public DeskDBStatement(DeskDBConnection connection) {
        this.connection = connection;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkClosed();
        
        // Parsear SQL simple: SELECT * FROM tabla [WHERE ...]
        try {
            String tableName = parseTableName(sql);
            if (tableName == null) {
                throw new SQLException("Invalid SELECT statement: " + sql);
            }

            // Ejecutar consulta en DeskDB
            var db = connection.getDeskDB();
            var results = db.table(tableName).select().execute();
            
            updateCount = -1;
            currentResultSet = new DeskDBResultSet(results, getColumnsForTable(db, tableName));
            return currentResultSet;
        } catch (Exception e) {
            throw new SQLException("Error executing query: " + e.getMessage(), e);
        }
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        checkClosed();
        
        try {
            String upperSql = sql.trim().toUpperCase();
            
            if (upperSql.startsWith("INSERT")) {
                return executeInsert(sql);
            } else if (upperSql.startsWith("UPDATE")) {
                return executeUpdateStmt(sql);
            } else if (upperSql.startsWith("DELETE")) {
                return executeDelete(sql);
            } else if (upperSql.startsWith("CREATE TABLE")) {
                return executeCreateTable(sql);
            } else if (upperSql.startsWith("DROP TABLE")) {
                return executeDropTable(sql);
            } else {
                throw new SQLException("Unsupported SQL statement: " + sql);
            }
        } catch (Exception e) {
            throw new SQLException("Error executing update: " + e.getMessage(), e);
        }
    }

    @Override
    public void close() throws SQLException {
        if (closed) {
            return;
        }
        
        if (currentResultSet != null) {
            try {
                currentResultSet.close();
            } catch (Exception e) {
                // Ignorar
            }
            currentResultSet = null;
        }
        
        closed = true;
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        checkClosed();
        return 0;
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        checkClosed();
        // No implementado
    }

    @Override
    public int getMaxRows() throws SQLException {
        checkClosed();
        return maxRows;
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        checkClosed();
        this.maxRows = max;
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        checkClosed();
        // No implementado
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        checkClosed();
        return 0;
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        checkClosed();
        // No implementado
    }

    @Override
    public void cancel() throws SQLException {
        checkClosed();
        // No implementado
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        checkClosed();
        return null;
    }

    @Override
    public void clearWarnings() throws SQLException {
        checkClosed();
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        checkClosed();
        // No implementado
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkClosed();
        
        String upperSql = sql.trim().toUpperCase();
        
        if (upperSql.startsWith("SELECT")) {
            executeQuery(sql);
            return true;
        } else {
            executeUpdate(sql);
            return false;
        }
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return execute(sql);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return execute(sql);
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        checkClosed();
        return currentResultSet;
    }

    @Override
    public int getUpdateCount() throws SQLException {
        checkClosed();
        return (int) updateCount;
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        checkClosed();
        return false;
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        checkClosed();
        if (direction != ResultSet.FETCH_FORWARD) {
            throw new SQLFeatureNotSupportedException("Only FETCH_FORWARD supported");
        }
    }

    @Override
    public int getFetchDirection() throws SQLException {
        checkClosed();
        return ResultSet.FETCH_FORWARD;
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        checkClosed();
        this.fetchSize = rows;
    }

    @Override
    public int getFetchSize() throws SQLException {
        checkClosed();
        return fetchSize;
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        checkClosed();
        return ResultSet.CONCUR_READ_ONLY;
    }

    @Override
    public int getResultSetType() throws SQLException {
        checkClosed();
        return ResultSet.TYPE_FORWARD_ONLY;
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        checkClosed();
        throw new SQLFeatureNotSupportedException("Batch operations not supported");
    }

    @Override
    public void clearBatch() throws SQLException {
        checkClosed();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        checkClosed();
        throw new SQLFeatureNotSupportedException("Batch operations not supported");
    }

    @Override
    public Connection getConnection() throws SQLException {
        if (closed) {
            throw new SQLException("Statement is closed");
        }
        return connection;
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        checkClosed();
        return false;
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        checkClosed();
        throw new SQLFeatureNotSupportedException("Generated keys not supported");
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        checkClosed();
        return ResultSet.CLOSE_CURSORS_AT_COMMIT;
    }

    @Override
    public boolean isClosed() throws SQLException {
        return closed;
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        checkClosed();
        // No implementado
    }

    @Override
    public boolean isPoolable() throws SQLException {
        checkClosed();
        return false;
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        checkClosed();
        // No implementado
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        checkClosed();
        return false;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (isWrapperFor(iface)) {
            return iface.cast(this);
        }
        throw new SQLException("Not a wrapper for " + iface.getName());
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }

    private void checkClosed() throws SQLException {
        if (closed) {
            throw new SQLException("Statement is closed");
        }
    }

    private String parseTableName(String sql) {
        // Parser muy básico: SELECT * FROM tablename
        String upperSql = sql.toUpperCase();
        int fromIndex = upperSql.indexOf("FROM");
        if (fromIndex == -1) {
            return null;
        }
        
        String afterFrom = sql.substring(fromIndex + 4).trim();
        int spaceIndex = afterFrom.indexOf(' ');
        if (spaceIndex == -1) {
            return afterFrom;
        }
        return afterFrom.substring(0, spaceIndex);
    }

    private String[] getColumnsForTable(com.deskdb.core.DeskDB db, String tableName) {
        try {
            var table = db.getTable(tableName);
            if (table != null) {
                return table.getSchema().getColumnNames().toArray(new String[0]);
            }
        } catch (IllegalStateException e) {
            // Tabla no existe, retornar array vacío
        } catch (Exception e) {
            // Ignorar otros errores
        }
        return new String[0];
    }

    private int executeInsert(String sql) throws SQLException {
        // Parser básico: INSERT INTO tabla (col1, col2) VALUES (val1, val2)
        int intoIndex = sql.toUpperCase().indexOf("INTO");
        if (intoIndex == -1) {
            throw new SQLException("Invalid INSERT statement");
        }
        
        String afterInto = sql.substring(intoIndex + 4).trim();
        int parenOpen = afterInto.indexOf('(');
        int parenClose = afterInto.indexOf(')');
        
        if (parenOpen == -1 || parenClose == -1) {
            throw new SQLException("Invalid INSERT syntax");
        }
        
        String tableName = afterInto.substring(0, parenOpen).trim();
        String columnsStr = afterInto.substring(parenOpen + 1, parenClose);
        String[] columns = columnsStr.split(",");
        
        for (int i = 0; i < columns.length; i++) {
            columns[i] = columns[i].trim();
        }
        
        // Encontrar VALUES
        int valuesIndex = sql.toUpperCase().indexOf("VALUES");
        if (valuesIndex == -1) {
            throw new SQLException("Missing VALUES clause");
        }
        
        String valuesStr = sql.substring(valuesIndex + 6).trim();
        int vParenOpen = valuesStr.indexOf('(');
        int vParenClose = valuesStr.lastIndexOf(')');
        
        if (vParenOpen == -1 || vParenClose == -1) {
            throw new SQLException("Invalid VALUES syntax");
        }
        
        String valuesContent = valuesStr.substring(vParenOpen + 1, vParenClose);
        String[] values = valuesContent.split(",");
        
        // Ejecutar insert
        var db = connection.getDeskDB();
        var tx = connection.getOrCreateTransaction();
        
        var insert = db.table(tableName).insert();
        for (int i = 0; i < columns.length && i < values.length; i++) {
            String col = columns[i];
            String val = values[i].trim();
            
            // Remover comillas si existen
            if ((val.startsWith("'") && val.endsWith("'")) || 
                (val.startsWith("\"") && val.endsWith("\""))) {
                val = val.substring(1, val.length() - 1);
            }
            
            // Intentar convertir a número
            Object typedValue = val;
            try {
                if (val.contains(".")) {
                    typedValue = Double.parseDouble(val);
                } else {
                    typedValue = Integer.parseInt(val);
                }
            } catch (NumberFormatException e) {
                // Mantener como string
            }
            
            insert.value(col, typedValue);
        }
        
        try {
            if (tx != null) {
                insert.execute(tx);
            } else {
                insert.execute();
            }
        } catch (Exception e) {
            throw new SQLException("Error al ejecutar INSERT", e);
        }
        
        return 1;
    }

    private int executeUpdateStmt(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("UPDATE not fully implemented yet");
    }

    private int executeDelete(String sql) throws SQLException {
        throw new SQLFeatureNotSupportedException("DELETE not fully implemented yet");
    }

    private int executeCreateTable(String sql) throws SQLException {
        // Parser básico: CREATE TABLE nombre (col1 tipo, col2 tipo)
        int tableIndex = sql.toUpperCase().indexOf("TABLE");
        if (tableIndex == -1) {
            throw new SQLException("Invalid CREATE TABLE statement");
        }
        
        String afterTable = sql.substring(tableIndex + 5).trim();
        int parenOpen = afterTable.indexOf('(');
        int parenClose = afterTable.lastIndexOf(')');
        
        // En DeskDB las tablas se crean automáticamente al insertar
        // Solo validamos la sintaxis SQL
        if (parenOpen == -1 || parenClose == -1) {
            throw new SQLException("Invalid CREATE TABLE syntax");
        }
        
        // Retornar éxito sin crear la tabla realmente
        return 0;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        checkClosed();
        return executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        checkClosed();
        return executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        checkClosed();
        return executeUpdate(sql);
    }

    private int executeDropTable(String sql) throws SQLException {
        // DeskDB no soporta DROP TABLE directamente
        // Las tablas se eliminan borrando el archivo de base de datos
        throw new SQLFeatureNotSupportedException("DROP TABLE not supported. Delete the .deskdb file instead.");
    }
}
