package com.deskdb.mapping;

import com.deskdb.mapping.annotations.Id;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.Serializable;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for ObjectStore functionality.
 */
public class ObjectStoreTest {

    private ObjectStore objectStore;

    @BeforeEach
    public void setUp() {
        objectStore = new ObjectStore();
    }

    @Test
    public void testPersistAndFindObject() {
        TestEntity entity = new TestEntity();
        entity.setName("Test Object");
        entity.setValue(42);

        Object id = objectStore.persist(entity);
        assertNotNull(id);

        TestEntity found = objectStore.find(TestEntity.class, id);
        assertNotNull(found);
        assertEquals("Test Object", found.getName());
        assertEquals(42, found.getValue());
        assertEquals(id, found.getId());
    }

    @Test
    public void testPersistMultipleObjects() {
        TestEntity entity1 = new TestEntity();
        entity1.setName("Entity 1");
        entity1.setValue(100);

        TestEntity entity2 = new TestEntity();
        entity2.setName("Entity 2");
        entity2.setValue(200);

        objectStore.persist(entity1);
        objectStore.persist(entity2);

        List<TestEntity> all = objectStore.findAll(TestEntity.class);
        assertEquals(2, all.size());
    }

    @Test
    public void testUpdateObject() {
        TestEntity entity = new TestEntity();
        entity.setName("Original");
        entity.setValue(10);

        objectStore.persist(entity);
        assertNotNull(entity.getId());

        entity.setName("Updated");
        entity.setValue(99);
        objectStore.update(entity);

        TestEntity found = objectStore.find(TestEntity.class, entity.getId());
        assertNotNull(found);
        assertEquals("Updated", found.getName());
        assertEquals(99, found.getValue());
    }

    @Test
    public void testRemoveObject() {
        TestEntity entity = new TestEntity();
        entity.setName("To Delete");
        entity.setValue(5);

        objectStore.persist(entity);
        Object id = entity.getId();

        boolean removed = objectStore.remove(entity);
        assertTrue(removed);

        TestEntity found = objectStore.find(TestEntity.class, id);
        assertNull(found);
    }

    @Test
    public void testRemoveByClassAndId() {
        TestEntity entity = new TestEntity();
        entity.setName("To Delete");
        entity.setValue(5);

        objectStore.persist(entity);
        Object id = entity.getId();

        boolean removed = objectStore.remove(TestEntity.class, id);
        assertTrue(removed);

        TestEntity found = objectStore.find(TestEntity.class, id);
        assertNull(found);
    }

    @Test
    public void testFindNonExistentObject() {
        TestEntity found = objectStore.find(TestEntity.class, 999L);
        assertNull(found);
    }

    @Test
    public void testFindAllEmpty() {
        List<TestEntity> all = objectStore.findAll(TestEntity.class);
        assertTrue(all.isEmpty());
    }

    @Test
    public void testClearAll() {
        TestEntity entity1 = new TestEntity();
        entity1.setName("Entity 1");
        TestEntity entity2 = new TestEntity();
        entity2.setName("Entity 2");

        objectStore.persist(entity1);
        objectStore.persist(entity2);

        objectStore.clear();

        List<TestEntity> all = objectStore.findAll(TestEntity.class);
        assertTrue(all.isEmpty());
    }

    @Test
    public void testClearByType() {
        TestEntity entity1 = new TestEntity();
        entity1.setName("Entity 1");
        AnotherEntity entity2 = new AnotherEntity();
        entity2.setDescription("Another");

        objectStore.persist(entity1);
        objectStore.persist(entity2);

        objectStore.clear(TestEntity.class);

        List<TestEntity> entities = objectStore.findAll(TestEntity.class);
        assertTrue(entities.isEmpty());

        List<AnotherEntity> others = objectStore.findAll(AnotherEntity.class);
        assertEquals(1, others.size());
    }

    @Test
    public void testAutoGeneratedIdsAreUnique() {
        TestEntity entity1 = new TestEntity();
        entity1.setName("Entity 1");

        TestEntity entity2 = new TestEntity();
        entity2.setName("Entity 2");

        objectStore.persist(entity1);
        objectStore.persist(entity2);

        assertNotEquals(entity1.getId(), entity2.getId());
    }

    // Test entity classes
    public static class TestEntity implements Serializable {
        @Id
        private Long id;
        private String name;
        private int value;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public int getValue() {
            return value;
        }

        public void setValue(int value) {
            this.value = value;
        }
    }

    public static class AnotherEntity implements Serializable {
        @Id
        private Long id;
        private String description;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }
    }
}
